services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: seucantinho_backend
    depends_on: 
      - seucantinho_db
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=seucantinho_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=seucantinho123
      - DB_NAME=seucantinho_db

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: seucantinho_client
    stdin_open: true
    tty: true

  seucantinho_db:
    image: postgres:17
    container_name: seucantinho_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seucantinho123
      POSTGRES_DB: seucantinho_db
    ports:
     - "5432:5432"
    volumes:
     - ./data:/var/lib/postgresql/data
     - ./server/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
